import styled, { css } from 'styled-components'
import { StandardLonghandPropertiesHyphen } from 'csstype'


export * from 'styled-components'

export type HiddenProperties = {
  [Property in keyof StandardLonghandPropertiesHyphen as `$${Property}`]: StandardLonghandPropertiesHyphen[Property]
}

export const PropsMixin = (props: HiddenProperties) => css`
  ${Object.entries(props).map(([key, value]) => {
    return css`
      ${key.replace('$', '')}: ${value};
    `
  })}
`

export const A = styled.a<HiddenProperties>(PropsMixin)
export const Abbr = styled.abbr<HiddenProperties>(PropsMixin)
export const Address = styled.address<HiddenProperties>(PropsMixin)
export const Area = styled.area<HiddenProperties>(PropsMixin)
export const Article = styled.article<HiddenProperties>(PropsMixin)
export const Aside = styled.aside<HiddenProperties>(PropsMixin)
export const Audio = styled.audio<HiddenProperties>(PropsMixin)
export const B = styled.b<HiddenProperties>(PropsMixin)
export const Base = styled.base<HiddenProperties>(PropsMixin)
export const Bdi = styled.bdi<HiddenProperties>(PropsMixin)
export const Bdo = styled.bdo<HiddenProperties>(PropsMixin)
export const Big = styled.big<HiddenProperties>(PropsMixin)
export const Blockquote = styled.blockquote<HiddenProperties>(PropsMixin)
export const Body = styled.body<HiddenProperties>(PropsMixin)
export const Br = styled.br<HiddenProperties>(PropsMixin)
export const Button = styled.button<HiddenProperties>(PropsMixin)
export const Canvas = styled.canvas<HiddenProperties>(PropsMixin)
export const Caption = styled.caption<HiddenProperties>(PropsMixin)
export const Cite = styled.cite<HiddenProperties>(PropsMixin)
export const Code = styled.code<HiddenProperties>(PropsMixin)
export const Col = styled.col<HiddenProperties>(PropsMixin)
export const Colgroup = styled.colgroup<HiddenProperties>(PropsMixin)
export const Data = styled.data<HiddenProperties>(PropsMixin)
export const Datalist = styled.datalist<HiddenProperties>(PropsMixin)
export const Dd = styled.dd<HiddenProperties>(PropsMixin)
export const Del = styled.del<HiddenProperties>(PropsMixin)
export const Details = styled.details<HiddenProperties>(PropsMixin)
export const Dfn = styled.dfn<HiddenProperties>(PropsMixin)
export const Dialog = styled.dialog<HiddenProperties>(PropsMixin)
export const Div = styled.div<HiddenProperties>(PropsMixin)
export const Dl = styled.dl<HiddenProperties>(PropsMixin)
export const Dt = styled.dt<HiddenProperties>(PropsMixin)
export const Em = styled.em<HiddenProperties>(PropsMixin)
export const Embed = styled.embed<HiddenProperties>(PropsMixin)
export const Fieldset = styled.fieldset<HiddenProperties>(PropsMixin)
export const Figcaption = styled.figcaption<HiddenProperties>(PropsMixin)
export const Figure = styled.figure<HiddenProperties>(PropsMixin)
export const Footer = styled.footer<HiddenProperties>(PropsMixin)
export const Form = styled.form<HiddenProperties>(PropsMixin)
export const H1 = styled.h1<HiddenProperties>(PropsMixin)
export const H2 = styled.h2<HiddenProperties>(PropsMixin)
export const H3 = styled.h3<HiddenProperties>(PropsMixin)
export const H4 = styled.h4<HiddenProperties>(PropsMixin)
export const H5 = styled.h5<HiddenProperties>(PropsMixin)
export const H6 = styled.h6<HiddenProperties>(PropsMixin)
export const Header = styled.header<HiddenProperties>(PropsMixin)
export const Hgroup = styled.hgroup<HiddenProperties>(PropsMixin)
export const Hr = styled.hr<HiddenProperties>(PropsMixin)
export const Html = styled.html<HiddenProperties>(PropsMixin)
export const I = styled.i<HiddenProperties>(PropsMixin)
export const Iframe = styled.iframe<HiddenProperties>(PropsMixin)
export const Img = styled.img<HiddenProperties>(PropsMixin)
export const Input = styled.input<HiddenProperties>(PropsMixin)
export const Ins = styled.ins<HiddenProperties>(PropsMixin)
export const Kbd = styled.kbd<HiddenProperties>(PropsMixin)
export const Keygen = styled.keygen<HiddenProperties>(PropsMixin)
export const Label = styled.label<HiddenProperties>(PropsMixin)
export const Legend = styled.legend<HiddenProperties>(PropsMixin)
export const Li = styled.li<HiddenProperties>(PropsMixin)
export const Link = styled.link<HiddenProperties>(PropsMixin)
export const Main = styled.main<HiddenProperties>(PropsMixin)
export const Map = styled.map<HiddenProperties>(PropsMixin)
export const Mark = styled.mark<HiddenProperties>(PropsMixin)
export const Menu = styled.menu<HiddenProperties>(PropsMixin)
export const Menuitem = styled.menuitem<HiddenProperties>(PropsMixin)
export const Meta = styled.meta<HiddenProperties>(PropsMixin)
export const Meter = styled.meter<HiddenProperties>(PropsMixin)
export const Nav = styled.nav<HiddenProperties>(PropsMixin)
export const Noscript = styled.noscript<HiddenProperties>(PropsMixin)
export const Obj = styled.object<HiddenProperties>(PropsMixin)
export const Ol = styled.ol<HiddenProperties>(PropsMixin)
export const Optgroup = styled.optgroup<HiddenProperties>(PropsMixin)
export const Option = styled.option<HiddenProperties>(PropsMixin)
export const Output = styled.output<HiddenProperties>(PropsMixin)
export const P = styled.p<HiddenProperties>(PropsMixin)
export const Param = styled.param<HiddenProperties>(PropsMixin)
export const Picture = styled.picture<HiddenProperties>(PropsMixin)
export const Pre = styled.pre<HiddenProperties>(PropsMixin)
export const Progress = styled.progress<HiddenProperties>(PropsMixin)
export const Q = styled.q<HiddenProperties>(PropsMixin)
export const Rp = styled.rp<HiddenProperties>(PropsMixin)
export const Rt = styled.rt<HiddenProperties>(PropsMixin)
export const Ruby = styled.ruby<HiddenProperties>(PropsMixin)
export const S = styled.s<HiddenProperties>(PropsMixin)
export const Samp = styled.samp<HiddenProperties>(PropsMixin)
export const Script = styled.script<HiddenProperties>(PropsMixin)
export const Section = styled.section<HiddenProperties>(PropsMixin)
export const Select = styled.select<HiddenProperties>(PropsMixin)
export const Small = styled.small<HiddenProperties>(PropsMixin)
export const Source = styled.source<HiddenProperties>(PropsMixin)
export const Span = styled.span<HiddenProperties>(PropsMixin)
export const Strong = styled.strong<HiddenProperties>(PropsMixin)
export const Style = styled.style<HiddenProperties>(PropsMixin)
export const Sub = styled.sub<HiddenProperties>(PropsMixin)
export const Summary = styled.summary<HiddenProperties>(PropsMixin)
export const Sup = styled.sup<HiddenProperties>(PropsMixin)
export const Table = styled.table<HiddenProperties>(PropsMixin)
export const Tbody = styled.tbody<HiddenProperties>(PropsMixin)
export const Td = styled.td<HiddenProperties>(PropsMixin)
export const Textarea = styled.textarea<HiddenProperties>(PropsMixin)
export const Tfoot = styled.tfoot<HiddenProperties>(PropsMixin)
export const Th = styled.th<HiddenProperties>(PropsMixin)
export const Thead = styled.thead<HiddenProperties>(PropsMixin)
export const Time = styled.time<HiddenProperties>(PropsMixin)
export const Tr = styled.tr<HiddenProperties>(PropsMixin)
export const Track = styled.track<HiddenProperties>(PropsMixin)
export const U = styled.u<HiddenProperties>(PropsMixin)
export const Ul = styled.ul<HiddenProperties>(PropsMixin)
export const Use = styled.use<HiddenProperties>(PropsMixin)
export const Var = styled.var<HiddenProperties>(PropsMixin)
export const Video = styled.video<HiddenProperties>(PropsMixin)
export const Wbr = styled.wbr<HiddenProperties>(PropsMixin)
export const Circle = styled.circle<HiddenProperties>(PropsMixin)
export const ClipPath = styled.clipPath<HiddenProperties>(PropsMixin)
export const Defs = styled.defs<HiddenProperties>(PropsMixin)
export const Ellipse = styled.ellipse<HiddenProperties>(PropsMixin)
export const ForeignObject = styled.foreignObject<HiddenProperties>(PropsMixin)
export const G = styled.g<HiddenProperties>(PropsMixin)
export const Image = styled.image<HiddenProperties>(PropsMixin)
export const Line = styled.line<HiddenProperties>(PropsMixin)
export const LinearGradient = styled.linearGradient<HiddenProperties>(PropsMixin)
export const Marker = styled.marker<HiddenProperties>(PropsMixin)
export const Mask = styled.mask<HiddenProperties>(PropsMixin)
export const Path = styled.path<HiddenProperties>(PropsMixin)
export const Pattern = styled.pattern<HiddenProperties>(PropsMixin)
export const Polygon = styled.polygon<HiddenProperties>(PropsMixin)
export const Polyline = styled.polyline<HiddenProperties>(PropsMixin)
export const RadialGradient = styled.radialGradient<HiddenProperties>(PropsMixin)
export const Rect = styled.rect<HiddenProperties>(PropsMixin)
export const Stop = styled.stop<HiddenProperties>(PropsMixin)
export const Svg = styled.svg<HiddenProperties>(PropsMixin)
export const Text = styled.text<HiddenProperties>(PropsMixin)
export const Tspan = styled.tspan<HiddenProperties>(PropsMixin)